module.exports = {
  branches: ["main"],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        // Bumps Cargo.toml's [workspace.package].version (every crate
        // inherits it) and generated/ts/package.json's version, then
        // regenerates Cargo.lock to match. See scripts/bump-version.sh.
        prepareCmd: "./scripts/bump-version.sh ${nextRelease.version}",
      },
    ],
    [
      "@semantic-release/git",
      {
        // generated/go + generated/ts are regenerated by release.yml as a
        // raw step before semantic-release runs (see that workflow's own
        // comment for why it's done there and not in a separately
        // triggered workflow) -- picked up here alongside the version
        // bump so one commit covers both, atomically.
        assets: ["Cargo.toml", "Cargo.lock", "generated/go/**", "generated/ts/**", "charts/magpie/Chart.yaml"],
        // Deliberately NOT `[skip ci]` -- that's a blanket GitHub
        // mechanism that skips *every* push-triggered workflow for this
        // commit, not just release.yml, and build-images.yml needs to
        // fire on exactly this commit (it's the one carrying the real
        // version tag). release.yml guards against re-triggering on its
        // own bump commit with an explicit `if:` on the commit message
        // prefix instead -- see that workflow's own comment.
        message: "chore(release): ${nextRelease.version}",
      },
    ],
    [
      "@semantic-release/github",
      {
        // The App token only has Contents: Read & Write -- successComment
        // (commenting on issues/PRs referenced by a release's commits)
        // needs issues/PR write access it doesn't have, which threw
        // "Resource not accessible by integration" in the plugin's
        // "success" step *after* the tag/release had already been
        // created successfully. That made the whole job report failure
        // anyway, which meant build-images.yml's workflow_run gate (only
        // triggers on conclusion == 'success') never fired -- a real
        // release existed with no images ever built for it. This
        // behavior is optional to the release itself; disable both
        // rather than grant the App broader permissions it doesn't
        // otherwise need.
        successComment: false,
        failComment: false,
      },
    ],
  ],
};
