module.exports = {
  branches: ["main"],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        // Bumps Cargo.toml's [workspace.package].version (every crate
        // inherits it) and generated/ts/package.json's version, then
        // regenerates Cargo.lock to match. See scripts/bump-version.sh.
        prepareCmd: "./scripts/bump-version.sh ${nextRelease.version}",
      },
    ],
    [
      "@semantic-release/git",
      {
        // generated/go + generated/ts are regenerated by release.yml as a
        // raw step before semantic-release runs (see that workflow's own
        // comment for why it's done there and not in a separately
        // triggered workflow) -- picked up here alongside the version
        // bump so one commit covers both, atomically.
        assets: ["Cargo.toml", "Cargo.lock", "generated/go/**", "generated/ts/**"],
        // [skip ci]: this push is App-authored (see release.yml), which
        // *does* trigger other workflows -- without this marker it would
        // re-trigger release.yml itself on its own version-bump commit.
        message: "chore(release): ${nextRelease.version} [skip ci]",
      },
    ],
    "@semantic-release/github",
  ],
};
