[package]
name = "volume-manager"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
axum = "0.8.9"
connectrpc = { version = "0.8.1", features = ["axum"] }
protocol = { path = "../../crates/protocol" }
tokio = { version = "1.53.0", features = ["rt-multi-thread", "macros", "net", "process", "sync", "fs"] }
tower = "0.5.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
