[package]
name = "authn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.103"
axum = "0.8.9"
jsonwebtoken = { version = "10.4.0", default-features = false, features = ["rust_crypto"] }
metrics = "0.24"
registry-db = { path = "../registry-db" }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres"] }
tracing = "0.1.44"
