[package]
name = "registry"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
authn = { path = "../../crates/authn" }
axum = "0.8.9"
buffa = "0.8.1"
connectrpc = { version = "0.8.1", features = ["axum"] }
crd = { path = "../../crates/crd" }
k8s-openapi = { version = "0.28.0", features = ["latest"] }
kube = { version = "4.0.0", features = ["derive"] }
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.18", default-features = false }
protocol = { path = "../../crates/protocol" }
registry-db = { path = "../../crates/registry-db" }
serde_json = "1.0.150"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "macros"] }
sync-client = { path = "../../crates/sync-client" }
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.53.0", features = ["rt-multi-thread", "macros", "net"] }
tower = "0.5.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["v7"] }
walkdir = "2.5.0"
workshop-parse = { path = "../../crates/workshop-parse" }
zip = "8.6.0"
