[package]
name = "steam-sync"
version.workspace = true
edition.workspace = true

[dependencies]
steamdepot = { git = "https://github.com/LinkIsGrim/steamdepot", rev = "fec00ce" }
tokio = { version = "1", features = ["rt", "sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
regex = "1"
anyhow = "1"
futures = "0.3"
tracing = "0.1"
serde_json = "1"
bincode = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
prost = "0.13"
walkdir = "2.5.0"
qrcode = { version = "0.14.1", default-features = false }
